config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :players do
    resources :stats, only: [:new, :create]
  end  
  resources :events

  root to: 'players#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  def start_time
    start_date
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :stats, dependent: :destroy

  
  validates :image, presence: true
  validates :name, presence: true
  validates :position, presence: true
  validates :birthday, presence: true
  validates :height, presence: true, numericality: { greater_than: 0 }
  validates :weight, presence: true, numericality: { greater_than: 0 }
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :player

  validates :at_bats, presence: true
  validates :at_hits, presence: true
  validates :rbis, presence: true
  validates :home_runs, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
         
  has_many :players
  has_many :events

  validates :team_name, presence: true
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:team_name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :index]
  include SimpleCalendar
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    Event.create(event_params)
    redirect_to events_path
  end
  private
  def event_params
    params.require(:event).permit(:title, :start_date).merge(user_id: current_user.id)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = user_signed_in? ? current_user.players : []
  end

  def new
    @player = Player.new
  end

  def create
    @player = current_user.players.build(player_params)
    if @player.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @stat = Stat.new
    @stats = @player.stats
  end

  def edit
  end

  def update
    if @player.update(player_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to root_path
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :position, :birthday, :height, :weight, :image).merge(user_id: current_user.id)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def create
    @stat = Stat.new(stat_params)
  if @stat.save
    redirect_to player_path(params[:player_id])
  else
    render :new
  end
  end


  def new
   @player = Player.find(params[:player_id]) 
   @stat = Stat.new
   
  end
  private
  def stat_params
    params.require(:stat).permit(:at_bats, :at_hits, :home_runs, :rbis, :innings_pitched, :earned_run).merge(player_id: params[:player_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/events/index.html.erb
<%= link_to "チーム日程を登録する", new_event_path(@user), class: "post" %>
<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>

  <% events.each do |event| %>
    <div>
      <%= event.title %>
    </div>
  <% end %>
<% end %>

app/views/events/new.html.erb
<%= form_with(model: @event, local: true) do |form| %>
  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_date %>

  </div>
  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseballApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <header class="header">
      
      <div class="header__bar row">
        <h1 class="header-logo"><a href="/">Baseball Management</a></h1>
       <div id="navArea">
    <nav>
      <div class="inner">
        <ul>
          <li><%=link_to "ホーム", root_path %></li>
          <!-- ログインしている場合にのみリンクを表示 -->
          <% if user_signed_in? %>
            <li><%= link_to "選手登録", new_player_path %></li>
            <li><%= link_to "チーム日程", events_path(@user) %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="toggle-btn">
      <span></span>
      <span></span>
      <span></span>
    </div>

    <div id="mask"></div>
  </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<div class="contents row">
  <div class="container">
    <div class="col-md-6 offset-md-3 text-center">
      <h3>選手を編集する</h3>
      <%= form_with(model: @player, local: true) do |form| %>
        <div class="form-group">
          <%= form.label :写真, class: "form-label" %>
          <%= form.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :選手名, class: "form-label" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :position, "ポジション", class: "form-label" %>
          <%= form.text_field :position, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :birthday, "生年月日", class: "form-label" %>
          <%= form.date_field :birthday, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :height, "身長", class: "form-label" %>
          <%= form.number_field :height, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :weight, "体重", class: "form-label" %>
          <%= form.number_field :weight, class: "form-control" %>
        </div>

        <%= form.submit "編集する", class: "post" %>
      <% end %>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<div class="index-main">
  
  <h1 class="title">野球チーム管理アプリ</h1>
  <div class="team">
    <% if user_signed_in? %>
      <p>ようこそ<%= current_user.team_name %>さん！</p>
    <% else %>
      <p>ようこそゲストさん！</p>
    <% end %>
  </div>

  <div class="player-contents">
    <h2 class="sub-title">選手一覧</h2>

    <ul class="player">
      <% @players.each do |player| %>
        <li class="list">
          <div class='item-img-content' onmouseover="showButtons(this)" onmouseout="hideButtons(this)">
            <%= image_tag player.image, class: "player-img" %>
            <span class="buttons">
              <%= link_to "編集", edit_player_path(player), class: "edit-button" %>
              <%= link_to "削除", player_path(player), data: { turbo_method: :delete }, class: "delete-button" %>
              <%= link_to "詳細", player_path(player), class: "show-button" %>
            </span>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= player.name %>
            </h3>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<script>
  function showButtons(element) {
    element.querySelector('.buttons').style.display = 'block';
  }

  function hideButtons(element) {
    element.querySelector('.buttons').style.display = 'none';
  }

  
</script>

app/views/players/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>選手を登録する</h3>
    <%= form_with(model: @player, local: true) do |form| %>
    <%= render 'shared/error_messages', model: form.object %>
      <div class="form-group">
        <%= form.label :写真, class: "form-label" %>
        <%= form.file_field :image, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :選手名, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :position, "ポジション", class: "form-label" %>
        <%= form.text_field :position, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :birthday, "生年月日", class: "form-label" %>
        <%= form.date_field :birthday, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :height, "身長", class: "form-label" %>
        <%= form.number_field :height, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :weight, "体重", class: "form-label" %>
        <%= form.number_field :weight, class: "form-control" %>
      </div>

      <%= form.submit "登録する", class: "post" %>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<div class="player-show">
  <div class="player-box">
    <h2 class="name"><%= @player.name %></h2>
    <div class="image">
      <%= image_tag @player.image ,class:"player-box-img" %>
    </div>

    <%= link_to "成績を登録する", new_player_stat_path(player_id: @player.id), class:"post"%>
     <table class="detail-table">
      <tbody>

      
      

        <tr>
          <th class="detail-item">ポジション</th>
          <td class="detail-value"><%= @player.position%></td>
        </tr>
        <tr>
          <th class="detail-item">生年月日</th>
          <td class="detail-value"><%= @player.birthday %></td>
        </tr>
        <tr>
          <th class="detail-item">身長</th>
          <td class="detail-value"><%= @player.height %></td>
        </tr>
        <tr>
          <th class="detail-item">体重</th>
          <td class="detail-value"><%= @player.weight %></td>
        </tr>
        
      
      </tbody>
      </table>
     
      <div class="stat-box">
   <h2 class="name">成績一覧</h2>
   
  <table class="detail-table">
    <tbody>
      <% @stats.each do |stat| %>
       <tr> 
        
        </tr>
        <tr>
          <th class="detail-item">打席</th>
          <td class="detail-value"><%= stat.at_bats %></td>
        </tr>
        <tr>
          <th class="detail-item">ヒット</th>
          <td class="detail-value"><%= stat.at_hits %></td>
        </tr>
        <tr>
          <th class="detail-item">ホームラン</th>
          <td class="detail-value"><%= stat.home_runs %></td>
        </tr>
        <tr>
          <th class="detail-item">打点</th>
          <td class="detail-value"><%= stat.rbis %></td>
        </tr>
        
        <tr>
          <th class="detail-item">投球回</th>
          <td class="detail-value"><%= stat.innings_pitched %></td>
        </tr>
        <tr>
          <th class="detail-item">自責点</th>
          <td class="detail-value"><%= stat.earned_run %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

     

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stats/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>成績を登録する</h3>
    <%= form_with(model: @stat, url: player_stats_path(@player), local: true) do |form| %>
      <%= form.hidden_field :player_id, value: params[:player_id] %>

      <div class="form-group">
        <%= form.label :at_bats, "打席", class: "form-label" %>
        <%= form.text_field :at_bats, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :at_hits, "ヒット", class: "form-label" %>
        <%= form.text_field :at_hits, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :home_runs, "ホームラン", class: "form-label" %>
        <%= form.text_field :home_runs, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :rbis, "打点", class: "form-label" %>
        <%= form.text_field :rbis, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :innings_pitched, "投球回", class: "form-label" %>
        <%= form.number_field :innings_pitched, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :earned_run, "自責点", class: "form-label" %>
        <%= form.number_field :earned_run, class: "form-control" %>
      </div>

      <%= form.submit "登録する", class: "post" %>
    <% end %>

    
  </div>
</div>